---
kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init

- name: build-permissions
  image: alpine
  environment:
    PKGS: python-boolean.py python-license-expression reuse
  commands:
    - if [ "$DRONE" == "true" ]; then chmod 777 $PKGS; fi
  depends_on:
  - submodules

- name: build-docker
  image: docker
  commands:
    - docker build -t aur-package-tester:latest .
  volumes:
  - name: dockersock
    path: /var/run/docker.sock

- name: python-boolean.py
  image: aur-package-tester:latest
  pull: if-not-exists
  environment:
    PKG: python-boolean.py
  commands:
  - namcap $PKG/PKGBUILD
  - python3 /home/builder/install_deps.py $PKG
  - cd $PKG
  - makepkg -sci --noconfirm
  depends_on:
  - submodules
  - build-permissions
  - build-docker

- name: python-license-expression
  image: aur-package-tester:latest
  pull: if-not-exists
  environment:
    PKG: python-license-expression
  commands:
  - namcap $PKG/PKGBUILD
  - python3 /home/builder/install_deps.py $PKG
  - cd $PKG
  - makepkg -sci --noconfirm
  depends_on:
  - submodules
  - build-permissions
  - build-docker

- name: reuse
  image: aur-package-tester:latest
  pull: if-not-exists
  environment:
    PKG: reuse
  commands:
  - namcap $PKG/PKGBUILD
  - python3 /home/builder/install_deps.py $PKG
  - cd $PKG
  - makepkg -sci --noconfirm
  - git clone https://github.com/fsfe/reuse-tool.git /tmp/reuse-tool
  - reuse --root /tmp/reuse-tool lint
  depends_on:
  - submodules
  - build-permissions
  - build-docker

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
