---
kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init

- name: build-permissions
  image: alpine
  environment:
    PKGS: python-boolean.py python-license-expression reuse
  commands:
    - if [ "$DRONE" == "true" ]; then chmod 777 $PKGS; fi
  depends_on:
  - submodules

- name: pull-docker
  image: mxmehl/aur-package-tester:latest
  commands:
    - md5sum /home/builder/install_deps.py

- name: python-boolean.py
  image: mxmehl/aur-package-tester:latest
  environment:
    PKG: python-boolean.py
  commands:
  - sudo pacman -Syu --noconfirm
  - namcap $PKG/PKGBUILD
  - python3 /home/builder/install_deps.py $PKG
  - cd $PKG
  - makepkg -sci --noconfirm
  depends_on:
  - submodules
  - build-permissions
  - pull-docker

- name: python-license-expression
  image: mxmehl/aur-package-tester:latest
  environment:
    PKG: python-license-expression
  commands:
  - sudo pacman -Syu --noconfirm
  - namcap $PKG/PKGBUILD
  - python3 /home/builder/install_deps.py $PKG
  - cd $PKG
  - makepkg -sci --noconfirm
  depends_on:
  - submodules
  - build-permissions
  - pull-docker

- name: reuse
  image: mxmehl/aur-package-tester:latest
  environment:
    PKG: reuse
  commands:
  - sudo pacman -Syu --noconfirm
  - namcap $PKG/PKGBUILD
  - python3 /home/builder/install_deps.py $PKG
  - cd $PKG
  - makepkg -sci --noconfirm
  - git clone https://github.com/fsfe/reuse-tool.git /tmp/reuse-tool
  - reuse --root /tmp/reuse-tool lint
  depends_on:
  - submodules
  - build-permissions
  - pull-docker
